"""empty message

Revision ID: 75f38cceef0f
Revises: fbcbbb660717
Create Date: 2023-06-20 12:19:17.486422

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '75f38cceef0f'
down_revision = 'fbcbbb660717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_datas', schema=None) as batch_op:
        batch_op.alter_column('experience',
               existing_type=sa.INTEGER(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
        batch_op.alter_column('number_of_projects',
               existing_type=sa.INTEGER(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
        batch_op.alter_column('number_of_customer',
               existing_type=sa.INTEGER(),
               type_=sa.SMALLINT(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_datas', schema=None) as batch_op:
        batch_op.alter_column('number_of_customer',
               existing_type=sa.SMALLINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('number_of_projects',
               existing_type=sa.SMALLINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('experience',
               existing_type=sa.SMALLINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
