"""empty message

Revision ID: cb7b43a9edb9
Revises: df69569ff081
Create Date: 2023-07-05 16:21:21.207698

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'cb7b43a9edb9'
down_revision = 'df69569ff081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=64), nullable=True))
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
