"""empty message

Revision ID: fbcbbb660717
Revises: c13241ba7f7a
Create Date: 2023-06-20 11:00:54.890978

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'fbcbbb660717'
down_revision = 'c13241ba7f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_datas',
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('number_of_projects', sa.Integer(), nullable=False),
    sa.Column('number_of_customer', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_datas')
    # ### end Alembic commands ###
